services:
  couchbase:
    image: btburnett3/couchbase-quickinit:enterprise-7.6.3
    container_name: fakeit-couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      CB_USERNAME: Administrator
      CB_PASSWORD: password
      CB_CLUSTER_NAME: FakeIt Cluster
      CB_SERVICES: kv,n1ql,index,fts
    volumes:
      - ./buckets.json:/startup/buckets.json:ro